services:

  database:
    image: mariadb:12
    container_name: silence-db
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_LARAVEL_USER}
      MARIADB_PASSWORD: ${DB_LARAVEL_PASSWORD}
    volumes:
      - silence-db-data:/var/lib/mysql
    networks:
      - silence-internal
    labels:
      - "traefik.enable=false"
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  application:
    build: ./backend
    container_name: silence-app
    env_file:
      - .env
    networks:
      - silence-internal
      - web
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=false"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  scheduler:
    build: ./backend
    container_name: silence-scheduler
    command: php artisan schedule:work
    env_file:
      - .env
    networks:
      - silence-internal
    labels:
      - "traefik.enable=false"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

volumes:
  silence-db-data:

networks:
  silence-internal:
    driver: bridge
  web:
    external: true
