services:

  database:
    image: mariadb
    container_name: silence-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - silence-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      timeout: 5s
      retries: 10

volumes:
  silence-db-data:
