tls:
  certificates:
    - certFile: /certs/silence.crt
      keyFile: /certs/silence.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/silence.crt
        keyFile: /certs/silence.key
